In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
import time

In [25]:
url = 'https://www.espncricinfo.com/series/indian-premier-league-2007-08-313494/match-schedule-fixtures-and-results'
page = requests.get(url)

soup = BeautifulSoup(page.text,'html')

print(soup)

<html><head>
<title>Access Denied</title>
</head><body>
<h1>Access Denied</h1>

You don't have permission to access "http://www.espncricinfo.com/series/indian-premier-league-2007-08-313494/match-schedule-fixtures-and-results" on this server.<p>
Reference #18.62a336a.1743782218.62bb58c
<p>https://errors.edgesuite.net/18.62a336a.1743782218.62bb58c</p>
</p></body>
</html>

In [22]:
table = soup.find_all("ul", id="team_archive")

In [40]:
data = pd.read_csv('ipl_data//matches.csv')

In [41]:
data.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [42]:
data.shape

(1095, 20)

In [43]:
data['team1'].value_counts()

team1
Royal Challengers Bangalore    135
Chennai Super Kings            128
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Kings XI Punjab                 92
Sunrisers Hyderabad             86
Delhi Daredevils                85
Delhi Capitals                  41
Deccan Chargers                 39
Punjab Kings                    31
Lucknow Super Giants            23
Pune Warriors                   23
Gujarat Titans                  21
Gujarat Lions                   16
Royal Challengers Bengaluru      9
Kochi Tuskers Kerala             7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Name: count, dtype: int64

In [44]:
data['team1'].value_counts()

team1
Royal Challengers Bangalore    135
Chennai Super Kings            128
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Kings XI Punjab                 92
Sunrisers Hyderabad             86
Delhi Daredevils                85
Delhi Capitals                  41
Deccan Chargers                 39
Punjab Kings                    31
Lucknow Super Giants            23
Pune Warriors                   23
Gujarat Titans                  21
Gujarat Lions                   16
Royal Challengers Bengaluru      9
Kochi Tuskers Kerala             7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Name: count, dtype: int64

In [18]:
data['team1'][0]

'Royal Challengers Bangalore'

In [53]:
for i in range(len(data['team1'])):
    if data['team1'][i] == 'Gujarat Lions':
        data['team1'][i] = 'Gujarat Titans'

In [54]:
data['team1'].value_counts()

team1
Royal Challengers Bangalore    144
Chennai Super Kings            128
Delhi Capitals                 126
Sunrisers Hyderabad            125
Punjab Kings                   123
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Gujarat Titans                  37
Pune Warriors                   23
Lucknow Super Giants            23
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Rising Pune Supergiant           7
Name: count, dtype: int64

In [55]:
data = data[~data['team1'].str.contains('Rising Pune Supergiant|Rising Pune Supergiants|Kochi Tuskers Kerala|Pune Warriors', na=False)]

In [18]:
ipl_data['team1'].nunique()

10

In [60]:
data['venue'].nunique()

57

In [62]:
data[data['super_over']=='Y']

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
66,392190,2009,Cape Town,2009-04-23,League,YK Pathan,Newlands,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,NaN,151.0,20.0,Y,NaN,MR Benson,M Erasmus
130,419121,2009/10,Chennai,2010-03-21,League,J Theron,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,Kings XI Punjab,tie,NaN,137.0,20.0,Y,NaN,K Hariharan,DJ Harper
328,598004,2013,Hyderabad,2013-04-07,League,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Sunrisers Hyderabad,tie,NaN,131.0,20.0,Y,NaN,AK Chaudhary,S Ravi
342,598017,2013,Bangalore,2013-04-16,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Royal Challengers Bangalore,tie,NaN,153.0,20.0,Y,NaN,M Erasmus,VA Kulkarni
416,729315,2014,Abu Dhabi,2014-04-29,League,JP Faulkner,Sheikh Zayed Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,tie,NaN,153.0,20.0,Y,NaN,Aleem Dar,AK Chaudhary
475,829741,2015,Ahmedabad,2015-04-21,League,SE Marsh,"Sardar Patel Stadium, Motera",Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,tie,NaN,192.0,20.0,Y,NaN,M Erasmus,S Ravi
610,1082625,2017,Rajkot,2017-04-29,League,KH Pandya,Saurashtra Cricket Association Stadium,Gujarat Titans,Mumbai Indians,Gujarat Lions,bat,Mumbai Indians,tie,NaN,154.0,20.0,Y,NaN,AK Chaudhary,CB Gaffaney
705,1175365,2019,Delhi,2019-03-30,League,PP Shaw,Arun Jaitley Stadium,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,tie,NaN,186.0,20.0,Y,NaN,AY Dandekar,Nitin Menon
746,1178426,2019,Mumbai,2019-05-02,League,JJ Bumrah,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,tie,NaN,163.0,20.0,Y,NaN,CK Nandan,S Ravi
757,1216493,2020/21,NaN,2020-09-20,League,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,158.0,20.0,Y,NaN,AK Chaudhary,Nitin Menon
765,1216547,2020/21,NaN,2020-09-28,League,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,202.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
790,1216512,2020/21,Abu Dhabi,2020-10-18,League,LH Ferguson,Sheikh Zayed Stadium,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,tie,NaN,164.0,20.0,Y,NaN,PG Pathak,S Ravi
791,1216517,2020/21,NaN,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,177.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
835,1254077,2021,Chennai,2021-04-25,League,PP Shaw,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,tie,NaN,160.0,20.0,Y,NaN,CB Gaffaney,KN Ananthapadmanabhan

In [63]:
ipl_data = data.drop(columns=['date','match_type','player_of_match','venue','super_over','method','umpire1','umpire2'],axis=1)

In [67]:
ipl_data.drop(columns=['id','target_overs'],axis=1,inplace=True)

In [73]:
ipl_data = ipl_data[~ipl_data['result'].str.contains('no result',na=False)]

In [74]:
ipl_data['result'].value_counts()

result
wickets    553
runs       479
Name: count, dtype: int64

In [14]:
ipl_data['team1'].value_counts()

team1
Royal Challengers Bangalore    139
Chennai Super Kings            127
Sunrisers Hyderabad            124
Punjab Kings                   123
Delhi Capitals                 123
Mumbai Indians                 121
Kolkata Knight Riders          117
Rajasthan Royals               100
Gujarat Titans                  36
Lucknow Super Giants            22
Name: count, dtype: int64

In [89]:
ipl_data["team2"].value_counts()

team2
Mumbai Indians                 131
Kolkata Knight Riders          124
Rajasthan Royals               113
Chennai Super Kings            105
Royal Challengers Bangalore     99
Sunrisers Hyderabad             90
Kings XI Punjab                 88
Delhi Daredevils                68
Delhi Capitals                  49
Deccan Chargers                 33
Punjab Kings                    25
Gujarat Titans                  24
Pune Warriors                   22
Lucknow Super Giants            21
Gujarat Lions                   12
Rising Pune Supergiant           9
Rising Pune Supergiants          7
Kochi Tuskers Kerala             6
Royal Challengers Bengaluru      6
Name: count, dtype: int64

In [94]:
ipl_data.to_csv("data/ipl_data.csv",index=False)

In [3]:
ipl_data = pd.read_csv("ipl_Data//ipl_data.csv")

In [4]:
ipl_data

,season,city,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs
0,2007/08,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0
1,2007/08,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0
2,2007/08,Delhi,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0
3,2007/08,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0
4,2007/08,Kolkata,Kolkata Knight Riders,Sunrisers Hyderabad,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0
...,...,...,...,...,...,...,...,...,...,...
983,2024,Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0
984,2024,Ahmedabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0
985,2024,Ahmedabad,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0
986,2024,Chennai,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0
987,2024,Chennai,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0

In [5]:
ipl_data['team2'].value_counts()

team2
Mumbai Indians                 131
Kolkata Knight Riders          124
Sunrisers Hyderabad            123
Delhi Capitals                 117
Punjab Kings                   113
Rajasthan Royals               113
Chennai Super Kings            105
Royal Challengers Bangalore    105
Gujarat Titans                  36
Lucknow Super Giants            21
Name: count, dtype: int64

In [20]:
for i in range(len(ipl_data['team2'])):
    if ipl_data['team2'][i] == 'Gujarat Lions':
        ipl_data['team2'][i] = 'Gujarat Titans'

In [22]:
ipl_data = ipl_data[~ipl_data['team2'].str.contains('Rising Pune Supergiant|Rising Pune Supergiants|Kochi Tuskers Kerala|Pune Warriors', na=False)]

In [16]:
ipl_data['team1'].value_counts()

team1
Royal Challengers Bangalore    133
Chennai Super Kings            123
Sunrisers Hyderabad            119
Punjab Kings                   118
Delhi Capitals                 118
Mumbai Indians                 113
Kolkata Knight Riders          112
Rajasthan Royals                96
Gujarat Titans                  34
Lucknow Super Giants            22
Name: count, dtype: int64

In [25]:
ipl_data.to_csv("ipl_Data/ipl_data.csv",index=False)

In [7]:
ipl_data.head(5)

,season,city,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs
0,2007/08,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0
1,2007/08,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0
2,2007/08,Delhi,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0
3,2007/08,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0
4,2007/08,Kolkata,Kolkata Knight Riders,Sunrisers Hyderabad,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0

In [8]:
ipl_data.dtypes

season            object
city              object
team1             object
team2             object
toss_winner       object
toss_decision     object
winner            object
result            object
result_margin    float64
target_runs      float64
dtype: object

In [9]:
ipl_data.isna().sum()

season            0
city             48
team1             0
team2             0
toss_winner       0
toss_decision     0
winner            0
result            0
result_margin     0
target_runs       0
dtype: int64

In [10]:
ipl_data.duplicated().sum()

np.int64(0)

In [11]:
ipl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         988 non-null    object
 1   city           940 non-null    object
 2   team1          988 non-null    object
 3   team2          988 non-null    object
 4   toss_winner    988 non-null    object
 5   toss_decision  988 non-null    object
 6   winner         988 non-null    object
 7   result         988 non-null    object
 8   result_margin  988 non-null    float64
 9   target_runs    988 non-null    float64
dtypes: float64(2), object(8)
memory usage: 77.3+ KB

In [12]:
ipl_data.drop(columns=['result'],axis=1,inplace=True)

In [13]:
ipl_data['winner'].value_counts()

winner
Mumbai Indians                 135
Chennai Super Kings            133
Kolkata Knight Riders          123
Rajasthan Royals               105
Royal Challengers Bangalore    105
Sunrisers Hyderabad             84
Kings XI Punjab                 79
Delhi Daredevils                61
Delhi Capitals                  45
Gujarat Titans                  28
Deccan Chargers                 25
Lucknow Super Giants            24
Punjab Kings                    24
Gujarat Lions                   10
Royal Challengers Bengaluru      7
Name: count, dtype: int64

In [23]:
for i in range(len(ipl_data['winner'])):
    if ipl_data['winner'][i] == 'Delhi Daredevils':
        ipl_data['winner'][i] = 'Delhi Capitals'

In [25]:
ipl_data['winner'].nunique()

10

In [26]:
obj_type = [col for col in ipl_data.columns if ipl_data[col].dtype == 'O']

In [27]:
obj_type

['season', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
train_data,test_data = train_test_split(ipl_data,test_size=0.2,random_state=42)

In [32]:
train_data

,season,city,team1,team2,toss_winner,toss_decision,winner,result_margin,target_runs
866,2023,Ahmedabad,Gujarat Titans,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,3.0,178.0
215,2011,Mumbai,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,6.0,176.0
294,2013,Kolkata,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Chennai Super Kings,4.0,120.0
49,2007/08,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Deccan Chargers,bat,Royal Challengers Bangalore,5.0,166.0
879,2023,Bengaluru,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,21.0,201.0
...,...,...,...,...,...,...,...,...,...
106,2009,Johannesburg,Royal Challengers Bangalore,Delhi Capitals,Delhi Daredevils,bat,Royal Challengers Bangalore,7.0,135.0
270,2012,Dharamsala,Punjab Kings,Delhi Capitals,Delhi Daredevils,field,Delhi Capitals,6.0,142.0
860,2023,Chennai,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,3.0,176.0
435,2015,Raipur,Delhi Capitals,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,6.0,164.0
102,2009,Johannesburg,Sunrisers Hyderabad,Kolkata Knight Riders,Deccan Chargers,field,Sunrisers Hyderabad,6.0,161.0

In [31]:
train_data.shape,test_data.shape

((790, 9), (198, 9))

In [ ]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from typing import List
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
import pickle
import os
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
TARGET_COLUMN = 'winner'
# Custom transformer to combine columns
class CombineCategoricals(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        # Combine all columns into a single DataFrame for consistent encoding
        return X.astype(str)



def save_object(file_path,obj):
    dir_path = os.path.dirname(file_path)
    os.makedirs(dir_path,exist_ok=True)
        
    with open(file_path,"wb") as file_obj:
        pickle.dump(obj,file_obj)


class DataCleaner:
    def __init__(self,df:pd.DataFrame):
        self.df = df
    
    def get_dtypes(self)->List:
        obj_col = [col for col in self.df.columns if self.df[col].dtype == 'O']
        num_col = [col for col in self.df.columns if self.df[col].dtype != 'O']
        return obj_col,num_col
    
    
    def create_class(self,obj_col,num_col):
        num_pipeline = Pipeline(
            steps=[
                ("scaler",StandardScaler())
            ]
        )
        
        cat_pipeline = Pipeline(
            steps=[
                ("imputer",SimpleImputer(strategy="most_frequent")),
                ("combine", CombineCategoricals()),
                ("ohe",OneHotEncoder(sparse_output=False))        
            ]
        )
        
        preprocessor = ColumnTransformer(
            transformers=[
                ("num_pipeline",num_pipeline,num_col),
                ("cat_pipeline",cat_pipeline,obj_col)
            ]
        )
        return preprocessor
    
    def initiate_transformation(self,train_data:pd.DataFrame,test_data:pd.DataFrame):
        input_feature_train = train_data.drop(columns=[TARGET_COLUMN],axis=1)
        output_feature_train = train_data[TARGET_COLUMN]
        input_feature_test = test_data.drop(columns=[TARGET_COLUMN],axis=1)
        output_feature_test = test_data[TARGET_COLUMN]
        cat_col,num_col = self.get_dtypes()
        preprocessor = self.create_class(obj_col=cat_col,num_col=num_col)
        train_arr = preprocessor.fit_transform(input_feature_train)
        test_arr = preprocessor.transform(input_feature_test)
        save_object(file_path="Artifacts/preprocessor.pkl",obj=preprocessor)
        
        return train_arr,test_arr

In [40]:
dc = DataCleaner(train_data)
train_arr,test_arr = dc.initiate_transformation(train_data=train_data,test_data=test_data)

In [44]:
obj_col = [col for col in ipl_data.columns if ipl_data[col].dtype == 'O']

In [48]:
# Get all unique categories from both input and target columns
unique_labels = pd.unique(
    pd.concat([train_data["team1"], train_data["team2"], train_data["winner"]])
)

# Use in OneHotEncoder
ohe = OneHotEncoder(categories=[unique_labels]*len(obj_col), handle_unknown="ignore", sparse_output=False)

In [50]:
unique_labels.reshape(1,-1)

array([['Gujarat Titans', 'Royal Challengers Bangalore',
        'Kolkata Knight Riders', 'Sunrisers Hyderabad', 'Punjab Kings',
        'Delhi Capitals', 'Chennai Super Kings', 'Rajasthan Royals',
        'Mumbai Indians', 'Lucknow Super Giants']], dtype=object)

In [51]:
unique_labels_encoded = ohe.fit_transform(unique_labels)

ValueError: Expected 2D array, got 1D array instead:
array=['Gujarat Titans' 'Royal Challengers Bangalore' 'Kolkata Knight Riders'
 'Sunrisers Hyderabad' 'Punjab Kings' 'Delhi Capitals'
 'Chennai Super Kings' 'Rajasthan Royals' 'Mumbai Indians'
 'Lucknow Super Giants'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [55]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

# Get all unique labels across input and target columns
unique_labels = pd.unique(
    pd.concat([train_data["team1"], train_data["team2"], train_data["winner"]])
)

# Reshape to 2D array
unique_labels_2d = unique_labels.reshape(-1, 1) if isinstance(unique_labels, np.ndarray) else unique_labels.to_numpy().reshape(-1, 1)

# Fit the encoder on the unique labels
ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
uq = ohe.fit_transform(unique_labels_2d)

# Optional: You can transform any data using the same encoder now
# example_encoded = ohe.transform(np.array(["Mumbai Indians", "Delhi Capitals"]).reshape(-1, 1))

In [57]:
unique_labels_2d

array([['Gujarat Titans'],
       ['Royal Challengers Bangalore'],
       ['Kolkata Knight Riders'],
       ['Sunrisers Hyderabad'],
       ['Punjab Kings'],
       ['Delhi Capitals'],
       ['Chennai Super Kings'],
       ['Rajasthan Royals'],
       ['Mumbai Indians'],
       ['Lucknow Super Giants']], dtype=object)

In [56]:
uq

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [43]:
train_arr

array([[-0.65405807,  0.31902226,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [-0.51396611,  0.25761203,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.60736075, -1.46187443,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.65405807,  0.25761203,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [-0.51396611, -0.11084935,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [-0.51396611, -0.2029647 ,  0.        , ...,  0.        ,
         0.        ,  1.        ]], shape=(790, 101))

In [2]:
ipl_data = pd.read_csv("ipl_Data//ipl_data.csv")

In [4]:
ipl_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         988 non-null    object
 1   city           940 non-null    object
 2   team1          988 non-null    object
 3   team2          988 non-null    object
 4   toss_winner    988 non-null    object
 5   toss_decision  988 non-null    object
 6   winner         988 non-null    object
 7   result         988 non-null    object
 8   result_margin  988 non-null    float64
 9   target_runs    988 non-null    float64
dtypes: float64(2), object(8)
memory usage: 77.3+ KB

In [8]:
ipl_data['team2'].value_counts()

team2
Mumbai Indians                 131
Kolkata Knight Riders          124
Sunrisers Hyderabad            123
Delhi Capitals                 117
Punjab Kings                   113
Rajasthan Royals               113
Chennai Super Kings            105
Royal Challengers Bangalore    105
Gujarat Titans                  36
Lucknow Super Giants            21
Name: count, dtype: int64

In [30]:
ipl_data['winner'].value_counts()

winner
Mumbai Indians                 135
Chennai Super Kings            133
Kolkata Knight Riders          123
Royal Challengers Bangalore    112
Sunrisers Hyderabad            109
Delhi Capitals                 106
Rajasthan Royals               105
Punjab Kings                   103
Gujarat Titans                  38
Lucknow Super Giants            24
Name: count, dtype: int64

In [37]:
for i in range(len(ipl_data['toss_winner'])):
    if ipl_data['toss_winner'][i] == 'Royal Challengers Bengaluru':
        ipl_data['toss_winner'][i] = 'Royal Challengers Bangalore'

In [39]:
ipl_data['toss_winner'].nunique()

10

In [41]:
ipl_data['city'].value_counts()

city
Mumbai            158
Kolkata            89
Delhi              84
Chennai            79
Hyderabad          71
Chandigarh         57
Bangalore          56
Jaipur             53
Ahmedabad          35
Abu Dhabi          35
Bengaluru          28
Pune               24
Durban             15
Dharamsala         13
Dubai              13
Lucknow            13
Visakhapatnam      12
Centurion          12
Sharjah            10
Navi Mumbai         9
Johannesburg        8
Port Elizabeth      7
Rajkot              7
Cuttack             6
Cape Town           6
Ranchi              6
Indore              6
Mohali              5
Raipur              5
Kanpur              4
Kimberley           3
East London         3
Nagpur              3
Guwahati            3
Bloemfontein        2
Name: count, dtype: int64

In [42]:
ipl_data

,season,city,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs
0,2007/08,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0
1,2007/08,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0
2,2007/08,Delhi,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,130.0
3,2007/08,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0
4,2007/08,Kolkata,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,5.0,111.0
...,...,...,...,...,...,...,...,...,...,...
983,2024,Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0
984,2024,Ahmedabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0
985,2024,Ahmedabad,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0
986,2024,Chennai,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0
987,2024,Chennai,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0

In [40]:
ipl_data[ipl_data['city'].isna()]

,season,city,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs
336,2014,NaN,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,146.0
339,2014,NaN,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,116.0
340,2014,NaN,Kolkata Knight Riders,Delhi Capitals,Kolkata Knight Riders,bat,Delhi Capitals,wickets,4.0,167.0
341,2014,NaN,Rajasthan Royals,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,7.0,192.0
343,2014,NaN,Punjab Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Punjab Kings,runs,72.0,194.0
344,2014,NaN,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,141.0
345,2014,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,151.0
346,2014,NaN,Sunrisers Hyderabad,Delhi Capitals,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,185.0
347,2014,NaN,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,142.0
350,2014,NaN,Delhi Capitals,Mumbai Indians,Mumbai Indians,bat,Delhi Capitals,wickets,6.0,126.0
351,2014,NaN,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,146.0
352,2014,NaN,Punjab Kings,Royal Challengers Bangalore,Punjab Kings,field,Punjab Kings,wickets,5.0,125.0
353,2014,NaN,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,173.0
656,2020/21,NaN,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,10.0,164.0
657,2020/21,NaN,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,runs,16.0,217.0
659,2020/21,NaN,Punjab Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Punjab Kings,runs,97.0,207.0
660,2020/21,NaN,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Delhi Capitals,runs,44.0,176.0
662,2020/21,NaN,Punjab Kings,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,224.0
664,2020/21,NaN,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,37.0,175.0
666,2020/21,NaN,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,7.0,165.0
668,2020/21,NaN,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,Delhi Capitals,runs,18.0,229.0
669,2020/21,NaN,Punjab Kings,Chennai Super Kings,Punjab Kings,bat,Chennai Super Kings,wickets,10.0,179.0
670,2020/21,NaN,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,runs,34.0,209.0
671,2020/21,NaN,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Capitals,runs,59.0,197.0
674,2020/21,NaN,Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,69.0,202.0
675,2020/21,NaN,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,field,Delhi Capitals,runs,46.0,185.0
677,2020/21,NaN,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,37.0,170.0
678,2020/21,NaN,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,wickets,5.0,159.0
680,2020/21,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,82.0,195.0
681,2020/21,NaN,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,168.0
682,2020/21,NaN,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,13.0,162.0
683,2020/21,NaN,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Punjab Kings,wickets,8.0,172.0
685,2020/21,NaN,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,bat,Delhi Capitals,wickets,5.0,180.0
686,2020/21,NaN,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,7.0,178.0
688,2020/21,NaN,Delhi Capitals,Punjab Kings,Delhi Capitals,bat,Punjab Kings,wickets,5.0,165.0
690,2020/21,NaN,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,155.0
691,2020/21,NaN,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,10.0,115.0
693,2020/21,NaN,Punjab Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Punjab Kings,runs,12.0,127.0
695,2020/21,NaN,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,146.0
696,2020/21,NaN,Kolkata Knight Riders,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,8.0,150.0
697,2020/21,NaN,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,88.0,220.0
699,2020/21,NaN,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,173.0
701,2020/21,NaN,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,5.0,121.0
702,2020/21,NaN,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,111.0
704,2020/21,NaN,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,60.0,192.0
706,2020/21,NaN,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,10.0,150.0
707,2020/21,NaN,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,201.0
710,2020/21,NaN,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,157.0

In [61]:
ipl_data['city'].value_counts()

city
Mumbai            158
Kolkata            89
Delhi              84
Chennai            79
Hyderabad          71
Chandigarh         57
Bangalore          56
Jaipur             53
Ahmedabad          35
Abu Dhabi          35
Bengaluru          28
Pune               24
Durban             15
Dharamsala         13
Dubai              13
Lucknow            13
Visakhapatnam      12
Centurion          12
Sharjah            10
Navi Mumbai         9
Johannesburg        8
Port Elizabeth      7
Rajkot              7
Cuttack             6
Cape Town           6
Ranchi              6
Indore              6
Mohali              5
Raipur              5
Kanpur              4
Kimberley           3
East London         3
Nagpur              3
Guwahati            3
Bloemfontein        2
Name: count, dtype: int64

In [63]:
ipl_data[ipl_data['city'].isna()]='Dubai'

In [89]:
ipl_data[ipl_data['city']=='Dubai']

,season,city,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs
336,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai
339,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai
340,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai
341,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai
343,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai,Dubai
...,...,...,...,...,...,...,...,...,...,...
759,2021,Dubai,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,3.0,137.0
762,2021,Dubai,Chennai Super Kings,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,6.0,135.0
765,2021,Dubai,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,165.0
766,2021,Dubai,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,4.0,173.0
769,2021,Dubai,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Chennai Super Kings,runs,27.0,193.0

In [66]:
ipl_data.to_csv("ipl_Data//ipl_data.csv",index=False)

In [75]:
df = pd.read_csv('ipl_Data//ipl_data.csv')

In [76]:
df_modified = df.drop(columns=['result','result_margin'],axis=1)

In [77]:
df_modified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         988 non-null    object
 1   city           988 non-null    object
 2   team1          988 non-null    object
 3   team2          988 non-null    object
 4   toss_winner    988 non-null    object
 5   toss_decision  988 non-null    object
 6   winner         988 non-null    object
 7   target_runs    988 non-null    object
dtypes: object(8)
memory usage: 61.9+ KB

In [ ]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from typing import List
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
import pickle
import os
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
TARGET_COLUMN = 'winner'
# Custom transformer to combine columns
class CombineCategoricals(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        # Combine all columns into a single DataFrame for consistent encoding
        return X.astype(str)



def save_object(file_path,obj):
    dir_path = os.path.dirname(file_path)
    os.makedirs(dir_path,exist_ok=True)
        
    with open(file_path,"wb") as file_obj:
        pickle.dump(obj,file_obj)


class DataCleaner:
    def __init__(self,df:pd.DataFrame):
        self.df = df
    
    def get_dtypes(self)->List:
        obj_col = [col for col in self.df.columns if self.df[col].dtype == 'O']
        num_col = [col for col in self.df.columns if self.df[col].dtype != 'O']
        return obj_col,num_col
    
    
    def create_class(self,obj_col,num_col):
        num_pipeline = Pipeline(
            steps=[
                ("scaler",StandardScaler())
            ]
        )
        
        cat_pipeline = Pipeline(
            steps=[
                ("imputer",SimpleImputer(strategy="most_frequent")),
                ("combine", CombineCategoricals()),
                ("ohe",OneHotEncoder())        
            ]
        )
        
        preprocessor = ColumnTransformer(
            transformers=[
                ("num_pipeline",num_pipeline,num_col)
                ("cat_pipeline",cat_pipeline,obj_col)
            ]
        )
        return preprocessor
    
    def initiate_transformation(self,train_data:pd.DataFrame,test_data:pd.DataFrame):
        # input_feature_train = train_data.drop(columns=[TARGET_COLUMN],axis=1)
        # output_feature_train = train_data[TARGET_COLUMN]
        # input_feature_test = test_data.drop(columns=[TARGET_COLUMN],axis=1)
        # output_feature_test = test_data[TARGET_COLUMN]
        cat_col,num_col = self.get_dtypes()
        preprocessor = self.create_class(obj_col=cat_col,num_col=num_col)
        train_arr = preprocessor.fit_transform(train_data)
        test_arr = preprocessor.transform(test_data)
        save_object(file_path="Artifacts/preprocessor.pkl",obj=preprocessor)
        
        return train_arr,test_arr

In [ ]:
# import pandas as pd
# from sklearn.preprocessing import OneHotEncoder

# # Sample DataFrame
# df = pd.DataFrame({
#     'color1': ['red', 'blue', 'green', 'blue'],
#     'color2': ['green', 'red', 'blue', 'green'],
#     'target': ['blue', 'green', 'red', 'red']
# })

# # Columns to encode (they share the same categories)
# shared_class_columns = ['color1', 'color2', 'target']

# # Step 1: Combine all values from the columns to get a complete set of categories
# all_values = pd.concat([df[col] for col in shared_class_columns], axis=0)
# unique_classes = pd.Series(all_values.unique())

# # Step 2: Fit OneHotEncoder on all combined data
# encoder = OneHotEncoder(sparse_output=False)
# encoder.fit(unique_classes.values.reshape(-1, 1))

# # Step 3: Encode each column separately but with the same encoder
# encoded_columns = {}
# for col in shared_class_columns:
#     transformed = encoder.transform(df[[col]])
#     col_names = [f"{col}_{cat}" for cat in encoder.categories_[0]]
#     encoded_df = pd.DataFrame(transformed, columns=col_names, index=df.index)
#     encoded_columns[col] = encoded_df

# # Step 4: Combine back into original dataframe
# df_encoded = pd.concat([df.drop(columns=shared_class_columns)] + list(encoded_columns.values()), axis=1)

# print(df_encoded)

   color1_blue  color1_green  color1_red  color2_blue  color2_green  \
0          0.0           0.0         1.0          0.0           1.0
1          1.0           0.0         0.0          0.0           0.0
2          0.0           1.0         0.0          1.0           0.0
3          1.0           0.0         0.0          0.0           1.0

   color2_red  target_blue  target_green  target_red
0         0.0          1.0           0.0         0.0
1         1.0          0.0           1.0         0.0
2         0.0          0.0           0.0         1.0
3         0.0          0.0           0.0         1.0

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder

# encoder = OrdinalEncoder()
# encoder.fit(unique_classes.values.reshape(-1, 1))

# # Apply to each column
# for col in shared_class_columns:
#     df[col + '_enc'] = encoder.transform(df[[col]])

In [79]:
cols = ['team1','team2','winner','toss_winner']
df_combined = pd.concat([df_modified[col] for col in cols],axis=0)

In [88]:
df_modified['winner'].value_counts()

winner
Mumbai Indians                 130
Chennai Super Kings            126
Kolkata Knight Riders          120
Royal Challengers Bangalore    106
Rajasthan Royals               102
Sunrisers Hyderabad            101
Delhi Capitals                  98
Punjab Kings                    95
Dubai                           48
Gujarat Titans                  38
Lucknow Super Giants            24
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

  color1 color2 target  color1_enc  color2_enc  target_enc
0    red  green   blue         2.0         1.0         0.0
1   blue    red  green         0.0         2.0         1.0
2  green   blue    red         1.0         0.0         2.0
3   blue  green    red         0.0         1.0         2.0